apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-annotator
subjects:
- kind: ServiceAccount
  name: pod-annotator
roleRef:
  kind: Role
  name: pod-annotator
  apiGroup: rbac.authorization.k8s.io